"""Create collection records

Revision ID: 0001
Revises:
Create Date: 2026-10-07 20:30:42.368225

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bins",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("lat", sa.Double(), nullable=False),
        sa.Column("lon", sa.Double(), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.CheckConstraint("lat BETWEEN -90 AND 90", name="ck_bins_lat_range"),
        sa.CheckConstraint("lon BETWEEN -180 AND 180", name="ck_bins_lon_range"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bins")),
    )
    op.create_table(
        "trucks",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("max_bins_per_trip", sa.Integer(), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.CheckConstraint("max_bins_per_trip > 0", name="ck_trucks_positive_capacity"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trucks")),
    )
    op.create_table(
        "routes",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("truck_id", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Text(), server_default=sa.text("'PLANNED'"), nullable=False
        ),
        sa.CheckConstraint(
            "status IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED')", name="ck_routes_status"
        ),
        sa.ForeignKeyConstraint(
            ["truck_id"], ["trucks.id"], name="fk_routes_truck_id", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routes")),
    )
    op.create_index("ix_routes_truck_id", "routes", ["truck_id"], unique=False)
    op.create_table(
        "route_stops",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("bin_id", sa.Integer(), nullable=False),
        sa.Column("stop_order", sa.Integer(), nullable=False),
        sa.CheckConstraint("stop_order > 0", name="ck_route_stops_positive_order"),
        sa.ForeignKeyConstraint(
            ["bin_id"], ["bins.id"], name="fk_route_stops_bin_id", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
            name="fk_route_stops_route_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_stops")),
        sa.UniqueConstraint(
            "route_id", "stop_order", name="uq_route_stops_route_order"
        ),
    )
    op.create_index("ix_route_stops_bin_id", "route_stops", ["bin_id"], unique=False)
    op.create_table(
        "service_events",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("bin_id", sa.Integer(), nullable=False),
        sa.Column("service_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fill_level", sa.Text(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "fill_level IN ('EMPTY', 'LESS_THAN_HALF', 'MORE_THAN_HALF', 'FULL')",
            name="ck_service_events_fill_level",
        ),
        sa.CheckConstraint("duration >= 0", name="ck_service_events_duration"),
        sa.ForeignKeyConstraint(
            ["bin_id"],
            ["bins.id"],
            name="fk_service_events_bin_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
            name="fk_service_events_route_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_events")),
    )
    op.create_index(
        "ix_service_events_bin_history",
        "service_events",
        ["bin_id", "service_ts", "id"],
        unique=False,
    )
    op.create_index(
        "ix_service_events_route_id", "service_events", ["route_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_service_events_route_id", table_name="service_events")
    op.drop_index("ix_service_events_bin_history", table_name="service_events")
    op.drop_table("service_events")
    op.drop_index("ix_route_stops_bin_id", table_name="route_stops")
    op.drop_table("route_stops")
    op.drop_index("ix_routes_truck_id", table_name="routes")
    op.drop_table("routes")
    op.drop_table("trucks")
    op.drop_table("bins")
    # ### end Alembic commands ###
